spring:
  application:
    name: t24-data-validation
  batch:
    initialize-schema: ALWAYS
    job:
      name: dataValidateJob
  profiles:
    active: @activatedProperties@
  data:
    jpa:
      repositories:
        enabled: false
# Uncomment the following line if needed
# main:
#   allow-bean-definition-overriding: true
max.chunk: 10
file:
  customer1: /data/AFTER TRANSFORM.txt
  customer2: CUSTOMER_SAMPLE10.txt
  headers:
    - \"ID\",\"NEW ID\",\"WITH CHANGES\",
    - \"CO CODE\",\"NEW CO CODE\",\"WITH CHANGES\",
    - \"MNEMONIC\",\"NEW MNEMONIC\",\"WITH CHANGES\",
    - \"SHORT NAME\",\"NEW SHORT NAME\",\"WITH CHANGES\",
    - \"NAME1\",\"NEW NAME1\",\"WITH CHANGES\",
    - \"NAME2\",\"NEW NAME2\",\"WITH CHANGES\"

  output-recon: D:/dftenerifejr/T24 Reimplementation/Data Validation/temp/output-recon.csv
  customer-fields:
    - id
    - coCode
    - mnemonic
    - shortName
    - name1
    - name2
    - street
    - address
    - townCountry
    - postCode
    - country
    - relationCode
    - relCustomer
    - relDelivOpt
    - role
    - roleMoreInfo
    - roleNotes
    - sector
    - accountOfficer
    - otherOfficer
    - industry
    - target
    - nationality
    - customerStatus
    - residence
    - contactDate
    - introducer
    - text
    - legalId
    - legalDocName
    - legalHolderName
    - legalIssAuth
    - legalIssDate
    - legalExpDate
    - offPhone
    - reviewFrequency
    - birthIncorpDate
    - globalCustomer
    - customerLiability
    - language
    - postingRestrict
    - dispoOfficer
    - companyBook
    - confidTxt
    - dispoExempt
    - issueCheques
    - clsCparty
    - fxCommGroupId
    - residenceRegion
    - customerRating
    - noUpdateCrm
    - title
    - givenNames
    - familyName
    - gender
    - dateOfBirth
    - maritalStatus
    - noOfDependents
    - phone1
    - sms1
    - email1
    - addrLocation
    - employmentStatus
    - occupation
    - jobTitle
    - employersName
    - employersAdd
    - employersBuss
    - employmentStart
    - customerCurrency
    - salary
    - annualBonus
    - salaryDateFreq
    - netMonthlyIn
    - netMonthlyOut
    - residenceStatus
    - residenceType
    - residenceSince
    - residenceValue
    - mortgageAmt
    - otherFinRel
    - otherFinInst
    - commType
    - prefChannel
    - allowBulkProcess
    - interests
    - fax1
    - previousName
    - changeDate
    - changeReason
    - customerSince
    - customerType
    - spokenLanguage
    - pastimes
    - furtherDetails
    - domicile
    - otherNationality
    - calcRiskClass
    - manualRiskClass
    - overrideReason
    - taxId
    - visType
    - visComment
    - visInternalReview
    - formerVisType
    - formerVisComment
    - riskAssetType
    - riskLevel
    - riskTolerance
    - riskFromDate
    - lastKycReviewDate
    - autoNextKycReviewDate
    - manualNextKycReviewDate
    - lastSuitReviewDate
    - autoNextSuitReviewDate
    - manualNextSuitReviewDate
    - kycRelationship
    - mandateAppl
    - mandateReg
    - mandateRecord
    - secureMessage
    - amlCheck
    - amlResult
    - lastAmlResultDate
    - kycComplete
    - internetBankingService
    - mobileBankingService
    - mergedTo
    - mergedStatus
    - externSysId
    - externCusId
    - lRegionCode
    - lAreaCode
    - lStateCode
    - lBirthPlace
    - segment
    - cuEffDate
    - lMiddleName
    - lSuffix
    - lCusBirPlc
    - lNameSpouse
    - lSpouseDob
    - lReligion
    - lSourceFund
    - lPerSt
    - lPlotNum
    - lCity
    - lPostCode
    - lCountry
    - lNetSalary
    - lNoYrService
    - lCustType
    - lNatBusiness
    - lCutOff
    - lProdCode
    - middleName
    - motherMdName
    - spouseName
    - lMotherMdNm
    - lSpouseName
    - lFirstName
    - lFamilyName
    - lNatOfWork
    - lNatEmploy
    - lSourceFunds
    - lPostalCode
    - lPsicInd
    - lAnnualIncome
    - lTotalAssets
    - lTotalLiab
    - lGrossRev
    - lIntExpense
    - lLandValue
    - lStockValue
    - lTotalExp
    - lNetIncome
    - lDeliveryMode
    - lSnrCitizen
    - lMjrStckHldr
    - lSeniorOfcr
    - lSignatories
    - lBenOwner
    - lDocSubmit
    - lSubmitDate
    - lDocType
    - lConstitution
    - lBspIndustry
    - lOfacCheck
    - lSpecimenSign
    - lNfis
    - lSnrCtzDt
    - lCustomerType
    - lDepSince
    - lBorrowSince
    - lEmpSector
    - lTinGss
    - lOtrOfclNm
    - lBnkName
    - lBnkBranch
    - lTypeDeposit
    - lDomicile
    - lDirectorName
    - lSnrOfficers
    - lMjStkHldr
    - lPosition
    - lBenefOwner
    - lSrcFdsBo
    - lDtBtBo
    - lPlBtBo
    - lNatWkBo
    - lAddBo
    - lDocuType
    - lLglDocNm
    - lDocuSubmit
    - lDocSubDt
    - lLegalId
    - lLglHldNm
    - lLglIssAut
    - lLglIssDate
    - lLglExpDate
    - lType
    - lSrNm
    - lFsNm
    - lMdNm
    - lPos
    - lContact
    - lPercent
    - lLegalNo
    - lLegalDoc
    - lLegalHolder
    - lLegalIssue
    - lIssueDate
    - lExpDate
    - lMaSt
    - lMaAdd
    - lMaTc
    - lMaPc
    - lMaRc
    - lMaAc
    - lMaSc
    - lMaCtry
    - lPaSt
    - lPaAdd
    - lPaTc
    - lPaPc
    - lPaRc
    - lPaAc
    - lPaSc
    - lPaCtry
    - lSssNo
    - lFinStDate
    - lDocuTypeCp
    - lLglDocNmCp
    - lDocSubmitCp
    - lDocSubDtCp
    - lLegalIdCp
    - lLglHldNmCp
    - lLglIssACp
    - lLglIssDCp
    - lLglExpDCp
    - lOccupation
    - lOccupation1
    - lMaPhone
    - lMaSms
    - lMaEmail
    - lTaxExempt
    - lShType
    - lShSrNm
    - lShFsNm
    - lShMdNm
    - lShPos
    - lShCnt
    - lShPercent
    - lShBirDate
    - lShBirPlace
    - lShNatWrk
    - lShSrcFunds
    - lShStreet
    - lShAddr
    - lShTc
    - lShPc
    - lShRc
    - lShAc
    - lShSc
    - lShCtry
    - lShLeglNo
    - lShLeglDoc
    - lShLeglHldr
    - lShLeglIssue
    - lShIssDate
    - lShExpDate
    - lPlaceIncorp
    - lAmlKyc
    - lArtiIncorp
    - lBoardRes
    - lBoardResSig
    - lBspRegist
    - lCorpByLaws
    - lCustInfoSh
    - lDisclosure
    - lDtiBusiness
    - lGenInfoSh
    - lIdOfSigna
    - lInvestPoli
    - lTrustAgrre
    - lSecCerti
    - lSecretaryCer
    - lSpecimanSig
    - lSuretyAggre
    - lMaRes
    - lMaMobile
    - lMaOffice
    - lMaFax
    - lHldMailFlag
    - ibsFlag
    - lBusName
    - lDteReg
    - lPlaceReg
    - lValidPeriod
    - lTnapMemNo
    - lTrustFlag
    - lTrustFlagDt
    - lTrustOnline
    - lExpVolTxn
    - lCompCode
    - lCustInstruct



