server.port: 0
spring:
  application:
    name: t24-data-validation
  batch:
    initialize-schema: ALWAYS
    job:
      name: dataValidateJob
  profiles:
    active: @activatedProperties@
  data:
    jpa:
      repositories:
        enabled: false
# Uncomment the following line if needed
# main:
#   allow-bean-definition-overriding: true




